- name: stop service syslog, if running
  systemd:
    name: rsyslog
    state: stopped
    enabled: false

- name: disable swap
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: disable zram swap
  lineinfile:
    path: /etc/default/armbian-zram-config
    regexp: '^SWAP='
    line: SWAP=false

- name: limit journald log size
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^RuntimeMaxUse='
    line: RuntimeMaxUse=20M

- name: limit journald log size
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^MaxLevelStore='
    line: MaxLevelStore=warning

- name: limit journald log size
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^MaxLevelSyslog='
    line: MaxLevelSyslog=warning
